"use client";

import { 
  TrendingUp, 
  TrendingDown, 
  Minus, 
  ShieldAlert, 
  BarChart3, 
  BrainCircuit, 
  AlertTriangle, 
  CheckCircle2, 
  Compass, 
  Layers 
} from "lucide-react";

interface ReportViewerProps {
  ticker: string;
  report: string; // The real markdown generated by your backend judge node
}

export default function ReportViewer({ ticker, report }: ReportViewerProps) {
  // 1. DYNAMIC REGEX EXTRACTION: Pull real content out of the LLM markdown output
  const extractSection = (regex: RegExp, fallback: string): string => {
    const match = report.match(regex);
    return match && match[1] ? match[1].trim() : fallback;
  };

  const tacticalRating = extractSection(/Tactical Rating:\*\*?\s*\[?([A-Za-z\s]+)\]?/i, "NEUTRAL");
// Replace this line in components/ReportViewer.tsx:
const targetWeight = extractSection(/Target Allocation Weight:\*\*?\s*\[?([0-9.]+%?)/i, "2.5%");
  const convictionScore = extractSection(/Conviction Score:\*\*?\s*\[?([0-9/.\s]+)\]?/i, "7");

  // Extract analyst summary sentences dynamically
  const valuationRiskText = extractSection(/Valuation & Risk:\*\*?\s*(.+)/i, "Reviewing quantitative balance data models.");
  const fundamentalGrowthText = extractSection(/Fundamental Growth:\*\*?\s*(.+)/i, "Assessing core income trajectories and performance trends.");
  const marketPsychologyText = extractSection(/Market Sentiment & Psychology:\*\*?\s*(.+)/i, "Tracking institutional media flows and narrative sentiment.");

  // Extract Strategic Thesis section dynamically
  let strategicThesis = "Generating complete architectural graph matrix synthesis...";
  const thesisMatch = report.split(/## Strategic Allocation Thesis/i);
  if (thesisMatch.length > 1) {
    strategicThesis = thesisMatch[1].trim();
  }

  // 2. DYNAMIC THEME ENGINE BASED ON TACTICAL RATING
  const isBullish = tacticalRating.toUpperCase().includes("BULLISH");
  const isBearish = tacticalRating.toUpperCase().includes("BEARISH");
  
  const badgeColors = isBullish 
    ? "bg-emerald-500/10 border-emerald-500/30 text-emerald-400 shadow-emerald-500/10" 
    : isBearish 
    ? "bg-rose-500/10 border-rose-500/30 text-rose-400 shadow-rose-500/10" 
    : "bg-amber-500/10 border-amber-500/30 text-amber-400 shadow-amber-500/10";

  const RatingIcon = isBullish ? TrendingUp : isBearish ? TrendingDown : Minus;
  
  // Safe numeric parsing for our score meter line
  const numericalScore = parseInt(convictionScore) || 7;

  return (
    <div className="space-y-6 animate-fade-in font-sans">
      
      {/* ZONE 1: DYNAMIC HERO BAR */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-2xl relative overflow-hidden">
        <div className="absolute -right-10 -top-10 w-40 h-40 bg-indigo-500/5 rounded-full blur-3xl pointer-events-none" />
        
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 border-b border-slate-800/80 pb-6">
          <div>
            <div className="flex items-center gap-2 text-xs font-mono uppercase tracking-wider text-slate-400">
              <Layers className="w-3.5 h-3.5 text-indigo-400" />
              <span>Multi-Agent Allocation Verdict</span>
            </div>
            <h1 className="text-3xl font-extrabold text-white mt-1 flex items-center gap-3">
              <span>{ticker}</span>
              <span className="text-slate-600 font-light">|</span>
              <span className="text-lg font-medium text-slate-300">Tactical Strategy</span>
            </h1>
          </div>

          {/* Dynamic Action Badge */}
          <div className={`flex items-center gap-2.5 px-5 py-2.5 rounded-xl border shadow-lg ${badgeColors}`}>
            <RatingIcon className="w-6 h-6 stroke-[2.5]" />
            <span className="font-bold tracking-wide text-lg uppercase">{tacticalRating}</span>
          </div>
        </div>

        {/* Quant Gauges Bar */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-6">
          <div className="bg-slate-950/50 rounded-xl p-4 border border-slate-800/60">
            <span className="text-xs font-medium text-slate-400 uppercase tracking-wider">Target Portfolio Weight</span>
            <div className="flex items-baseline gap-2 mt-2">
              <span className="text-2xl font-bold text-white font-mono">{targetWeight}</span>
            </div>
            <div className="w-full bg-slate-800 h-1.5 rounded-full mt-3 overflow-hidden">
              <div className="bg-indigo-500 h-full rounded-full" style={{ width: isBullish ? "80%" : isBearish ? "20%" : "50%" }} />
            </div>
          </div>

          <div className="bg-slate-950/50 rounded-xl p-4 border border-slate-800/60">
            <span className="text-xs font-medium text-slate-400 uppercase tracking-wider">Model Conviction Score</span>
            <div className="flex items-baseline gap-2 mt-2">
              <span className="text-2xl font-bold text-indigo-400 font-mono">{convictionScore}</span>
              <span className="text-xs text-slate-500">/ 10.0 Max</span>
            </div>
            <div className="flex gap-1 mt-3">
              {[...Array(10)].map((_, i) => (
                <div 
                  key={i} 
                  className={`h-1.5 flex-1 rounded-sm ${i < numericalScore ? "bg-indigo-400" : "bg-slate-800"}`} 
                />
              ))}
            </div>
          </div>

          <div className="bg-slate-950/50 rounded-xl p-4 border border-slate-800/60 flex flex-col justify-between">
            <span className="text-xs font-medium text-slate-400 uppercase tracking-wider">Agent Consensus Engine</span>
            <div className="flex items-center gap-2 mt-1 text-sm text-slate-300">
              <CheckCircle2 className="w-4 h-4 text-indigo-400 flex-shrink-0" />
              <span>3 Specialist Models Synthesized</span>
            </div>
            <span className="text-[11px] text-slate-500 font-mono">GROQ LLAMA-3.3 • MISTRAL-SMALL</span>
          </div>
        </div>
      </div>

      {/* ZONE 2: DYNAMIC MULTI-AGENT INTELLIGENCE CARDS */}
      <div className="space-y-3">
        <h3 className="text-sm font-bold uppercase tracking-wider text-slate-400 flex items-center gap-2 px-1">
          <Compass className="w-4 h-4 text-indigo-400" />
          <span>Specialist Domain Audit</span>
        </h3>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          
          {/* Card 1: Risk & Valuation */}
          <div className="bg-slate-900/90 border border-slate-800 rounded-xl p-5 space-y-3 relative overflow-hidden flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                <div className="flex items-center gap-2 font-bold text-slate-200 text-sm">
                  <ShieldAlert className="w-4 h-4 text-amber-400" />
                  <span>Risk & Valuation</span>
                </div>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-slate-950 text-slate-400 border border-slate-800">
                  Audit Trace
                </span>
              </div>
              <p className="text-xs text-slate-300 mt-3 leading-relaxed">
                {valuationRiskText.replace(/^[*\s]+/, "")}
              </p>
            </div>
            <div className="pt-3 border-t border-slate-800/60 text-[11px] font-mono text-slate-500">
              NODE: GROQ / LLAMA-3.3-70B
            </div>
          </div>

          {/* Card 2: Growth & Fundamentals */}
          <div className="bg-slate-900/90 border border-slate-800 rounded-xl p-5 space-y-3 relative overflow-hidden flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                <div className="flex items-center gap-2 font-bold text-slate-200 text-sm">
                  <BarChart3 className="w-4 h-4 text-indigo-400" />
                  <span>Fundamentals</span>
                </div>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-slate-950 text-slate-400 border border-slate-800">
                  Audit Trace
                </span>
              </div>
              <p className="text-xs text-slate-300 mt-3 leading-relaxed">
                {fundamentalGrowthText.replace(/^[*\s]+/, "")}
              </p>
            </div>
            <div className="pt-3 border-t border-slate-800/60 text-[11px] font-mono text-slate-500">
              NODE: GROQ / GEMMA-2-9B
            </div>
          </div>

          {/* Card 3: Market Sentiment */}
          <div className="bg-slate-900/90 border border-slate-800 rounded-xl p-5 space-y-3 relative overflow-hidden flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                <div className="flex items-center gap-2 font-bold text-slate-200 text-sm">
                  <BrainCircuit className="w-4 h-4 text-emerald-400" />
                  <span>Market Psychology</span>
                </div>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-slate-950 text-slate-400 border border-slate-800">
                  Audit Trace
                </span>
              </div>
              <p className="text-xs text-slate-300 mt-3 leading-relaxed">
                {marketPsychologyText.replace(/^[*\s]+/, "")}
              </p>
            </div>
            <div className="pt-3 border-t border-slate-800/60 text-[11px] font-mono text-slate-500">
              NODE: MISTRAL-SMALL
            </div>
          </div>

        </div>
      </div>

      {/* ZONE 3: DYNAMIC STRATEGIC THESIS */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-4">
        <div className="border-b border-slate-800 pb-4">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span>Portfolio Manager Synthesis & Strategic Thesis</span>
          </h2>
          <p className="text-xs text-slate-400 mt-0.5">
            Full reasoning context emitted by the consensus judge node.
          </p>
        </div>

        {/* Dynamic Text Output Area */}
        <div className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-slate-300 space-y-4 max-h-[400px] overflow-y-auto pr-2 custom-scrollbar">
          {strategicThesis}
        </div>
      </div>

    </div>
  );
}